### ISSUE TITLE
Правила линтинга блока warning, пункт 3

### ISSUE THREAD

**Issue by RuslanGerasimov** [yndx-shri-reviewer/shri-2020-task-2#1]
![yndx-shri-reviewer shri-2020-task-2  Задание 2  Напишите линтер — ШРИ  Москва  2020](https://user-images.githubusercontent.com/27442911/70180663-860ab700-16f1-11ea-98f8-a67833bab653.png)
Описание ошибки не соответствует примеру правильной / неправильной структуры. В описание говорится, что button не может находиться перед блоком placeholder, а в примере структуры такой вариант отмечен как правильный. Подскажите, пожалуйста, как должно быть.

**Comment by yndx-shri-reviewer** [comment]
Ошибка была в примере, спасибо большое за вопрос, ошибка исправлена
