### ISSUE TITLE
Не валидный JSON

### ISSUE THREAD

**Issue by IlyaChudin** [yndx-shri-reviewer/shri-2020-task-2#10]
Что должна возвращать функция `lint`, если JSON не валиден? Пустой массив или какую-то произвольную ошибку?

**Comment by MOTORIST** [comment]
По условию он всегда валидный. Так что Ваше на усмотрение.

**Comment by yndx-shri-reviewer** [comment]
Можете обработать данную ситуацию по вашему усмотрению. То, что вы ее  обработаете  - хорошо, специальных требований как это сделать - нет
