### ISSUE TITLE
Блок button в блоке warning

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-2#11]
Здравствуйте!
Считается ли, что блок button лежит на том же уровне, что и placeholder?
![image](https://user-images.githubusercontent.com/17002069/71190699-20dcc700-2296-11ea-9cbb-35cc2c647ae3.png)

**Comment by yndx-shri-reviewer** [comment]
Блоки могут лежать на любом  уровне  вложенности
