### ISSUE TITLE
Внешние зависимости

### ISSUE THREAD

**Issue by bemdev** [yndx-shri-reviewer/shri-2020-task-2#12]
Приветствую! А прям вообще ничего внешне нельзя? даже json-to-ast ? Стоит ли разбивать файловую структуру так же по "блокам"  с условием проверки и тестом?

**Comment by mikhin** [comment]
Кажется, что можно, но нужно чтоб в итоге всё было в едином бандле.

**Comment by yndx-shri-reviewer** [comment]
В задании написано:
> Мы не ограничиваем вас в выборе технологий, фреймворков и библиотек. Пожалуйста, для каждого выбранного инструмента напишите краткое обоснование: зачем он нужен в вашем проекте, и почему именно он.

> Стоит ли разбивать файловую структуру так же по "блокам" с условием проверки и тестом?

 Организация проекта остается на ваше усмотрение,  сделайте как считаете нужным. Правильная организация структуры - одна из частей задания,  на которую мы будем обращать внимание при проверке
