### ISSUE TITLE
Размер кнопки блока warning должен быть на 1 шаг больше эталонного

### ISSUE THREAD

**Issue by andrei-korolev** [yndx-shri-reviewer/shri-2020-task-2#14]
Здравствуйте, подскажите пожалуйста
Размер кнопки блока warning должен быть на 1 шаг больше эталонного (например, для размера l таким значением будет xl).

В качестве эталонного может быть только блок `text` с каким-то size? или любой блок у которого есть size, допустим блок `placeholder` имеет `size` его считать эталонным? Или если нет блока `text`, то эталонного размера нет?
Спасибо.

**Comment by yndx-shri-reviewer** [comment]
В  задании написано:
> Все тексты (блоки text) в блоке warning должны быть одного размера, то есть c одинаковым значением модификатора size, и этот размер должен быть определен. Размер первого из таких элементов в форме будем считать эталонным.

То есть только блоки text.  Если их нет - можно сделать ошибку с кодом на ваше усмотрение
