### ISSUE TITLE
Расчет позиции ошибки в примере, значение "end"

### ISSUE THREAD

**Issue by nat-k-dev** [yndx-shri-reviewer/shri-2020-task-2#15]
Подскажите, пожалуйста, почему в [примере](https://github.com/yndx-shri-reviewer/shri-2020-task-2#%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%B8-%D0%B2%D1%8B%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85) позиция end содержит column = 2? 

`"end": { "column": 2, "line": 22 }`

В примере видно, что блок заканчивается закрывающейся фигурной скобкой на 22 строке, которая находится в  колонке номер 1, а не 2. Почему все-таки "2"?

**Comment by nat-k-dev** [comment]
Аналогично column в sublime. Закрываю.

**Comment by rakov-di** [comment]
@appalse а можно поподробнее, почему? Закрывающаяся скобка блока "}" находится в колонке 1 (и в sublime, и вообще). В любом случае, в данном примере она в той же колонке что и открывающая блок скобка "{", а она в первой колонке `"start": { "column": 1, "line": 1 },`
@yndx-shri-reviewer или надо указывать позицию, следующую после "}"?

**Comment by nat-k-dev** [comment]
@rakov-di , я думаю, что это некий стандарт, считать колонки не символами, а позициями куда курсор может встать. Если подвигать курсор по строке в Sublime,  в Visual Studio Code, то перед закрывающейся скобкой будет 1, после нее - 2. Так как конец объекта после закрывающейся скобки (то есть объект в себя включает фигурные скобки), то колонка будет = 2.

**Comment by rakov-di** [comment]
@appalse спасибо. Надо просто принять как факт.
