### ISSUE TITLE
Провал автотестов

### ISSUE THREAD

**Issue by bemdev** [yndx-shri-reviewer/shri-2020-task-2#19]
Приветствую!

Автотесты провалились так

![Снимок экрана 2020-01-07 в 19 46 10](https://user-images.githubusercontent.com/20998840/71907915-7534e180-3186-11ea-90e9-fcbaea43c7c8.png)

В связи с этим можно как то узнать подробности по первому и последнему пункту. Что именно не так в путях и блоке warning?

Написаны собственные тесты вроде как на все требования и они проходят.

Подскажите пожалуйста, куда смотреть конкретнее.

**Comment by yndx-shri-reviewer** [comment]
Мы не открываем тесты, которые проверяют правильность выполненного задания.  Общий совет такой:
* Еще раз перечитать задание и уточнить все ли правила учтены
* Написать свои тесты для проверки вашего кода
* Обратить внимание на обработку краевых случаев
