### ISSUE TITLE
Формат записи имени модификатора

### ISSUE THREAD

**Issue by ElizabethSvit** [yndx-shri-reviewer/shri-2020-task-2#2]
Кажется, что в [таких примерах](https://github.com/yndx-shri-reviewer/shri-2020-task-2/blame/master/README.md#L121) имя модификатора size должно быть в кавычках (или это не гарантируется и запись может быть как в кавычках, так и без?).

**Comment by yndx-shri-reviewer** [comment]
Да, в примерах была опечатка, сейчас примеры поправлены
