### ISSUE TITLE
Вопрос по входным данным

### ISSUE THREAD

**Issue by kidonrage** [yndx-shri-reviewer/shri-2020-task-2#20]
Входным JSON может являться массив, а не объект? Как в этом примере:
`[
    // неправильно
    {
        "block": "text",
        "mods": { "type": "h3" }
    },
    {
        "block": "text",
        "mods": { "type": "h2" }
    }
]`

Или же валидным является только полученный на вход объект?

**Comment by nat-k-dev** [comment]
В задании указано, что на вход подается строка, string. В Issue упоминали, что в строке всегда валидный json. Как я понимаю, в строке на самом верхнем уровне может быть и массив, и объект. Я использую стороннюю библиотеку для парсинга входных данных. Тесты warning проходят, а тесты заголовков падают, предположительно из-за того, что входные данные отличаются от данных для проверки блока warning.
Вопрос к @yndx-shri-reviewer , 
1) какой еще возможен тип данных верхнего уровня (после парсинга строки), кроме объекта и массива (фигурные и квадратные скобки)?
2)  возможны ли комментарии внутри json?

**Comment by frontstall** [comment]
> В задании указано, что на вход подается строка, string. В Issue упоминали, что в строке всегда валидный json. Как я понимаю, в строке на самом верхнем уровне может быть и массив, и объект. Я использую стороннюю библиотеку для парсинга входных данных. Тесты warning проходят, а тесты заголовков падают, предположительно из-за того, что входные данные отличаются от данных для проверки блока warning.

Можно обернуть парсинг в try catch, в catch вернуть пустой массив и посмотреть, как поменяется вывод тестов. Спойлер: никак, все тестовые данные парсятся нормально. У меня тоже заголовки ни одного теста не проходят, хотя локально все работает и на примерах, и на произвольных файлах bemjson. Неделю уже дебажу :(

**Comment by yndx-shri-reviewer** [comment]
> Входным JSON может являться массив, а не объект? Как в этом примере:
> `[ // неправильно { "block": "text", "mods": { "type": "h3" } }, { "block": "text", "mods": { "type": "h2" } } ]`
> 
> Или же валидным является только полученный на вход объект?

Корневым элементом всегда является объект

**Comment by yndx-shri-reviewer** [comment]
> В задании указано, что на вход подается строка, string. В Issue упоминали, что в строке всегда валидный json. Как я понимаю, в строке на самом верхнем уровне может быть и массив, и объект. Я использую стороннюю библиотеку для парсинга входных данных. Тесты warning проходят, а тесты заголовков падают, предположительно из-за того, что входные данные отличаются от данных для проверки блока warning.
> Вопрос к @yndx-shri-reviewer ,
> 
> 1. какой еще возможен тип данных верхнего уровня (после парсинга строки), кроме объекта и массива (фигурные и квадратные скобки)?
> 2. возможны ли комментарии внутри json?

1 Только объект
2 Нет
