### ISSUE TITLE
Количество ошибок

### ISSUE THREAD

**Issue by kidonrage** [yndx-shri-reviewer/shri-2020-task-2#21]
Пример с анализом количества заголовков первого уровня: на вход поступает контент, состоящий из 3-х заголовков h1. Линтер должен вернуть две ошибки (с позициями 2 и 3 заголовков) или одну (с позицией первого найденного не валидного заголовка, то есть второго) ?

**Comment by yndx-shri-reviewer** [comment]
2 ошибки с позициями 2 и 3 заголовков
