### ISSUE TITLE
Вопросы по условию "Заголовок второго уровня не может находиться перед заголовком первого уровня"

### ISSUE THREAD

**Issue by Aracturat** [yndx-shri-reviewer/shri-2020-task-2#23]
В условии сказано:

> Заголовок второго уровня (блок text с модификатором type h2) не может находиться перед заголовком первого уровня на том же или более глубоком уровне вложенности.

1. К чему здесь относиться фраза **"на том же или более глубоком уровне вложенности"**, к заголовку h1 или заголовку h2? 

2. Считается ли валидной данная разметка?
```json
[
    {
        "block": "text",
        "mods": { "type": "h2" }
    },
    { 
        "block": "test",
        "content": {
            "block": "text",
            "mods": { "type": "h1" }
        }
    }
]
```

3. Считается ли валидной данная разметка?
```json
[
    { 
        "block": "test",
        "content": {
            "block": "text",
            "mods": { "type": "h2" }
        }
    },
    {
        "block": "text",
        "mods": { "type": "h1" }
    }
]
```

**Comment by skazko** [comment]
Присоединяюсь к вопросу.

**Comment by nat-k-dev** [comment]
Присоединяюсь.

**Comment by ViktorKugay** [comment]
Уточните, пожалуйста, где именно должны начинаться и заканчиваться маркеры для невалидных блоков? Написал большое кол-во тестов для для линтинга текстовых блоков, но автотесты shri показывают 0 из 8. Можно ли получить более информативный лог?

**Comment by alyonafomenkova** [comment]
У меня тот же вопрос.

**Comment by MOTORIST** [comment]
А в семантической верстке блок h1 может быть ниже h2?

**Comment by yndx-shri-reviewer** [comment]
1. Если находим  h2 - смотрим на его соседей и всех детей соседей на предмет нахождения там h1 и валидируем
2. нет
3. да
