### ISSUE TITLE
Вопрос по условию "Все тексты в блоке warning должны быть одного размера"

### ISSUE THREAD

**Issue by kidonrage** [yndx-shri-reviewer/shri-2020-task-2#24]
Если в рамках одного блока warning три блока текста, и два последних по размеру отличаются от первого, линтер должен возвращать 2 ошибки (с одинаковым полем location, получается) или одну?

**Comment by frontstall** [comment]
> Если в рамках одного блока warning три блока текста, и два последних по размеру отличаются от первого, линтер должен возвращать 2 ошибки (с одинаковым полем location, получается) или одну?

> Позиция ошибки: в качестве позиций start и end необходимо указать позицию первого и последнего символов ошибочного блока warning в строке.

Могу предположить, что не нужно искать все нарушения этого правила в блоке, если цель - подчеркнуть весь блок. Нашли первую ошибку, подчеркнули блок, поехали дальше.

**Comment by kidonrage** [comment]
@frontstall тоже так предполагаю, но хотел бы уточнить у @yndx-shri-reviewer , ведь если предположение неверно, тесты могут валиться

**Comment by yndx-shri-reviewer** [comment]
@frontstall прав, одну
