### ISSUE TITLE
Логи ошибок

### ISSUE THREAD

**Issue by victor-kugay** [yndx-shri-reviewer/shri-2020-task-2#28]
Добрый день.

Никаких логов об ошибках кроме тех, что можно найти в личном кабинете по адресу `https://account.shri.yandex/` не предусмотрено? Некоторые тесты падают, но хотелось бы знать какие именно кейсы не обработаны в моем коде. 

Спасибо за ответ)

**Comment by nat-k-dev** [comment]
Вот [тут ](https://github.com/yndx-shri-reviewer/shri-2020-task-2/issues/19) уже отвечали.

**Comment by yndx-shri-reviewer** [comment]
логов ошибок для второго задания мы не предоставляем
