### ISSUE TITLE
Линтер корректно валидирует пропорции функциональных и рекламных блоков: пройдено 1 из 2 тестов

### ISSUE THREAD

**Issue by bemdev** [yndx-shri-reviewer/shri-2020-task-2#29]
Добрый день, коллеги!

А есть тот кто прошел тесты по рекламным блокам? Вы проверяли валидность входного json? Или какой то дополнительный тест помимо проверки размерности колонок и наличия только одного блока?

Не могу понять, что еще требуется проверить в этом задании. Может кто то посоветовать, что еще нужно тестировать, что бы пройти этот пункт?

**Comment by frontstall** [comment]
Джейсон валидный, тесты проходят. Возможно, стоит ещё раз прочитать задание.
