### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ElizabethSvit** [yndx-shri-reviewer/shri-2020-task-2#3]
[Здесь](https://github.com/yndx-shri-reviewer/shri-2020-task-2/blame/master/README.md#L149) скорее всего имелся в виду блок placeholder.

**Comment by mikhin** [comment]
@yndx-shri-reviewer, подскажите, так ли это?

**Comment by yndx-shri-reviewer** [comment]
Да, опечатку поправили
