### ISSUE TITLE
Сброс автотестов

### ISSUE THREAD

**Issue by mpoliakov** [yndx-shri-reviewer/shri-2020-task-2#30]
Здравствуйте!

Можно ли сбросить автотесты после успешного прохождения для задания 2? Написал через форму обратной связи (frontendschool@yandex-team.ru), но не получил ответа.

Анкета кандидата в ШРИ: Поляков Максим Владимирович
Репозиторий: https://github.com/mpoliakov/shri-2020-task-2

**Comment by Godis715** [comment]
Присоединяюсь к вопросу
Потребность в сбросе автотестов возникла по той же причине, что указана в #4

**Comment by dvdvdmt** [comment]
@Godis715 напиши на frontendschool@yandex-team.ru с указанием своего репозитория и их сбросят.

**Comment by mpoliakov** [comment]
@dvdvdmt я написал, но так и не получил ответа, поэтому продублировал сюда в надежде, что среагируют.

**Comment by yndx-shri-reviewer** [comment]
Сбросить после отправки на проверку уже нельзя. Отправка на  проверку означает, что задание полностью готово и преподаватель может приступить к его проверке и возможно оно уже проверено. Преподаватель запустит еще раз автотесты руками на  последней версии кода, когда будет смотреть работу.

**Comment by mpoliakov** [comment]
@yndx-shri-reviewer но я ещё не отправил на проверку преподавателем...
