### ISSUE TITLE
Валидация текстовых блоков

### ISSUE THREAD

**Issue by victor-kugay** [yndx-shri-reviewer/shri-2020-task-2#31]
@yndx-shri-reviewer, добрый день)) 

Я написал большое количество тестов для кейсов, связанных с валидацей текстовых блоков, валидировал json-ы из задания shri-1, однако, автотесты показывают 0 из 8 пройденных тестов. 

Судя по всему мой код падает с некоторой ошибкой, т.к. после постановки 
`try {} catch { return []; }`  как минимум 3 теста уже проходят. 

Спасибо.

**Comment by ViktorKugay** [comment]
Виладные тесты: 

>{
    "block": "warning",
    "content": [
        {
            "block": "text",
            "mods": { "type": "h1" }
        }
    ]
}

>[
  {
    "block": "text",
    "mods": { "type": "h1" }
  }
]

>{
  "block": "text",
  "mods": { "type": "h1" }
}

>{
  "block": "grid",
  "mods": {
      "m-columns": "10"
  },
  "content": [
      {
          "block": "grid",
          "elem": "fraction",
          "elemMods": {
              "m-col": "8"
          },
          "content": [
              {
                  "block": "payment",
                  "content": [
                    {
                      "block": "text",
                      "mods": { "type": "h1" }
                    }
                  ]
              }
          ]
      },
      {
          "block": "grid",
          "elem": "fraction",
          "elemMods": {
              "m-col": "2"
          },
          "content": [
              {
                  "block": "offer",
                  "content": [
                    {
                      "block": "text",
                      "mods": { "type": "h1" }
                    }
                  ]
              }
          ]
      }
  ]
}

**Comment by nat-k-dev** [comment]
У меня тоже самое. Написано 26 тестов на заголовки, в том числе тесты из задания. И тоже по заголовкам 0 из 8, остальные проходят. При этом когда был отправлен алгоритм с ошибками, в т.ч. использование необъявленной переменной, все автотесты прошли успешно.

**Comment by ViktorKugay** [comment]
![Uploading Screenshot from 2020-01-13 21-43-32.png…]()
![Uploading Screenshot from 2020-01-13 21-43-38.png…]()
![Screenshot from 2020-01-13 21-43-57](https://user-images.githubusercontent.com/58416487/72284024-14f3e300-3651-11ea-9ed2-3c2754ae00f9.png)
![Uploading Screenshot from 2020-01-13 21-44-07.png…]()

**Comment by victor-kugay** [comment]
@appalse Мой вариант падает с ошибкой, т.к. после try catch хотя бы три теста поднялись, а вот такой вариант, с referenceError - уже более интересно))

**Comment by nat-k-dev** [comment]
@ViktorKugay а вы запускали на двух json'ах из 1 задания?

**Comment by victor-kugay** [comment]
@appalse Да. Страницу *product* у меня валидируется без ошибок, *index* содержит некоторые ошибки, но не связанные с текстовыми блоками, т.к. там нет ни одного заголовка.

**Comment by frontstall** [comment]
> @appalse Да. Страницу _product_ у меня валидируется без ошибок, _index_ содержит некоторые ошибки, но не связанные с текстовыми блоками, т.к. там нет ни одного заголовка.

Такая же история. 0 из 8 при локально зеленых тестах и 3 из 8 при отсутствии валидации вообще :)

**Comment by nat-k-dev** [comment]
Видимо, надо поискать, где может быть обращение в полям объекта в состоянии undefined

**Comment by nat-k-dev** [comment]
![icons8-костыль-50](https://user-images.githubusercontent.com/8708553/72324091-3984a500-36bb-11ea-9a87-cdd54f034fa1.png)
wanted

**Comment by yndx-shri-reviewer** [comment]
Если ваши тесты проходят, а наши автотесты нет - скорее всего дело в сборке  и  внешних зависимостях
