### ISSUE TITLE
Уровень вложенности для правил.

### ISSUE THREAD

**Issue by neomad1337** [yndx-shri-reviewer/shri-2020-task-2#33]
Я правильно понял что для правил WARNING.TEXT_SIZES_SHOULD_BE_EQUAL и WARNING.INVALID_BUTTON_SIZE, необходимо проверять не глубже первого уровня? 
т.е. такой блок не валидный
`{
    "block": "warning",
    "content": [
        { "block": "text", "mods": { "size": "l" } },
        { "block": "text", "mods": { "size": "xl" } }
    ]
}`

а такой валидный
`{
    "block": "warning",
    "content": [
        { "block": "text", "mods": { "size": "l" } },
        { "block": "wrapper", "content": [
               { "block": "text", "mods": { "size": "xl" } }
           ]
        }
    ]
}`

**Comment by mpoliakov** [comment]
Поддерживаю вопрос. Делал проверку только на 1-м уровне, не спускался глубже, и все тесты прошли.

**Comment by yndx-shri-reviewer** [comment]
нужно проверять во всех потомках,  на любых уровнях вложенностях
 @mpoliakov ваш код написан  с ошибкой
