### ISSUE TITLE
Проверка блока GRID

### ISSUE THREAD

**Issue by burlaknastia** [yndx-shri-reviewer/shri-2020-task-2#35]
При проверки валидности блока `grid`, позицию ошибки выводить как позицию всего блока (родительского) или позицию маркетингового блока?

> Код ошибки: `GRID.TOO_MUCH_MARKETING_BLOCKS`
Позиция ошибки: в качестве позиций start и end необходимо указать позицию первого и последнего символов ошибочного блока grid.

**Comment by artemloiko** [comment]
@burlaknastia  Должно быть все таки всего grid
> позицию первого и последнего символов ошибочного **блока grid**

**Comment by burlaknastia** [comment]
@artuom130 маркетинговый блок лежит в блоке grid
```js
{
           "block": "grid",
           "elem": "fraction",
           "elemMods": {
               "m-col": "2"
           },
           "content": [
               {
                   "block": "offer"
               }
           ]
}
```
получается - позиция ошибочного блока `grid` - это позиция дочернего блока, в котором лежит контентный, или родительского `grid`?

**Comment by artemloiko** [comment]
@burlaknastia 

В этом случае позиция родительского `grid`.
Потому что этот дочерний блок `grid` на самом деле является элементом блока `grid`, т.к. у него есть свойство ` "elem": "fraction"`

**Comment by bemdev** [comment]
> @burlaknastia
> 
> В этом случае позиция родительского `grid`.
> Потому что этот дочерний блок `grid` на самом деле является элементом блока `grid`, т.к. у него есть свойство ` "elem": "fraction"`

Вроде непонятно, что будет правильно. Тесты и так и так проходят без дополнительных ошибок в этом разделе или разделе "путей". Хотя логика, что это элемент ошибочного блока grid правильна.

**Comment by yndx-shri-reviewer** [comment]
В задании сказано:
Позиция ошибки: в качестве позиций start и end необходимо указать позицию первого и последнего символов ошибочного блока **grid**.
