### ISSUE TITLE
Блок warning провал тестов

### ISSUE THREAD

**Issue by bemdev** [yndx-shri-reviewer/shri-2020-task-2#36]
Добрый день. 

<img width="870" alt="Снимок экрана 2020-01-16 в 11 10 57" src="https://user-images.githubusercontent.com/20998840/72501797-3c190300-3851-11ea-8d09-0e62ffa828d9.png">

Что то тупик)

Написал собственных тестов вроде уже на все случаи жизни этого блока и разные вложенные warning в warning и в другие и без значений и со значениями. Но тесты никак не пройду. Может кто то знает секрет, какой то (какая нибудь супер уникальная ситуация) в тестах. Подскажите будьте так любезны. Задание зачитал уже до кровавых глаз )

**Comment by yndx-shri-reviewer** [comment]
Могу посоветовать: обратить внимание на  краевые случаи и написать тесты под каждое правило. В вашем коде на момент написания правила были ошибки

**Comment by andrei-korolev** [comment]
@bemdev  у моих тестов 1 в 1 такие же значения, тоже варнинг 33 и дальше не понятно

**Comment by bemdev** [comment]
> @bemdev у моих тестов 1 в 1 такие же значения, тоже варнинг 33 и дальше не понятно

Не знаю заругают за подсказки нет) но важная фраза "краевые случаи". Внимательнее проверь - допустим, есть ли вообще модификатор или его значения и какие они.
