### ISSUE TITLE
Сброс автотестов

### ISSUE THREAD

**Issue by mpoliakov** [yndx-shri-reviewer/shri-2020-task-2#38]
Можно ли сбросить автотесты для задания 2? Автотесты прошли успешно, на проверку преподавателем НЕ отправлял (предыдущий мой issue закрыли по этой причине). Сделал рефакторинг и хотел бы проверить себя ещё раз. Видел, что по таким же запросам тесты сбрасывали. Спасибо.

Анкета кандидата в ШРИ: Поляков Максим Владимирович
Репозиторий: https://github.com/mpoliakov/shri-2020-task-2

**Comment by yndx-shri-reviewer** [comment]
Сбросили
