### ISSUE TITLE
Автотесты для GRID.TOO_MUCH_MARKETING_BLOCKS

### ISSUE THREAD

**Issue by playhardgopro** [yndx-shri-reviewer/shri-2020-task-2#4]
Написал все правила линтинга, кроме 
`GRID.TOO_MUCH_MARKETING_BLOCKS`
и отправил на автотесты - было интересно посмотреть сколько пройдет. И все автотесты прошли, отсюда вопросы:
1. Возможно стоит доработать автотесты для `GRID.TOO_MUCH_MARKETING_BLOCKS`?
2. Могу ли я не отправлять решение на ревью преподавателю, а еще раз запустить автотесты (сейчас доступно только отправить на ручную проверку)?
3. После ручной проверки сразу выставляется оценка или есть возможность доработать код?

Спасибо :)

**Comment by oreshkin-ay** [comment]
@playhardgopro привет) 
https://github.com/yndx-shri-reviewer/shri-2020-task-2/issues/5 можешь посмотреть?) ты как делал, что у тебя автотесты прошли)

**Comment by yndx-shri-reviewer** [comment]
1. Смотрю на результат Ваших тестов от 7 декабря, в них не все автотесты прошли, но этого достаточно, чтобы работа смогла быть отправлена на проверку преподавателю.
2. Cейчас нет возможности запустить автотесты еще раз, если они уже прошли. Мы добавим её, но позже. Вы можете отрефакторить код и написать нам, мы сбросим результат автотестов вручную. Также лучше написать для проверки работоспособности кода свои тесты - это один из критериев хорошо выполненной работы.
3. После отправки  на ручную проверку - работа в течении нескольких дней будет проверена, поэтому отправлять следует уже полностью готовую работу со всеми необходимыми правками
