### ISSUE TITLE
Блок warning

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-2#5]
Здравствуйте! 
Если блок warning вложен в другой блок warning, возвращаем положение вложенного блока (2) или родительского (1) ?
![Screenshot_8](https://user-images.githubusercontent.com/17002069/70493330-5b1cca80-1b18-11ea-86a4-311b65c570e9.png)

**Comment by playhardgopro** [comment]
Привет) Нужно выводить положение блока, в котором произошла ошибка. По идее это ближайший блок warning вверх по вложенности

**Comment by playhardgopro** [comment]
@oreshkin-ay 17 декабря будет трансляция, там можно будет задать все вопросы)

**Comment by oreshkin-ay** [comment]
@playhardgopro до 17 слишком долго) ответь еще, пожалуйста, про h2)

**Comment by yndx-shri-reviewer** [comment]
Нужно выводить положение блока, в котором произошла ошибка, @playhardgopro прав
