### ISSUE TITLE
Позиция ошибки

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-2#6]
Правильно ли понимаю, что надо вернуть позицию всего блока? Или надо вернуть позицию h2?
![image](https://user-images.githubusercontent.com/17002069/70497996-113ae100-1b26-11ea-95ff-8108260d7ce7.png)

**Comment by playhardgopro** [comment]
Да, вернуть надо позицию блока (внешний прямоугольник) 
:)

**Comment by yndx-shri-reviewer** [comment]
Все  верно, позицию всего блока
