### ISSUE TITLE
Вопросы по BEMJSON

### ISSUE THREAD

**Issue by MOTORIST** [yndx-shri-reviewer/shri-2020-task-2#7]
Пример:

```
{
  "block": "header",
  "content": {
      "block": "header",
      "elem": "content",
      "content": [
          {
              "block": "header",
              "elem": "logo"
          },
          [
              {
                  "block": "onoffswitch",
                  "mods": {
                      "checked": true
                  },
                  "content": [
                      {
                          "block": "onoffswitch",
                          "elem": "button"
                      }
                  ]
              }
          ]
      ]
  }
}
```
Почему content может принимать как объект, так и массив? Не проще ли всегда массив, даже если содержимое одно?

Для какой цели блок onoffswitch обернут в массив? Убрал массив в верстке ничего не поменялось.

**Comment by yndx-shri-reviewer** [comment]
> Почему content может принимать как объект, так и массив? Не проще ли всегда массив, даже если содержимое одно?

Это особенность реализации BEMJSON, который допускает возможность использования как объектов, так и массивов.

> Для какой цели блок onoffswitch обернут в массив? Убрал массив в верстке ничего не поменялось.

Это особенность шаблона блоков header и onoffswitch в наших шаблонах, на основании которых шаблонизатор bemtree генерирует json'ы страниц.
