### ISSUE TITLE
Автотетсты

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-2#8]
День добрый! 
Мой вопрос схож с https://github.com/yndx-shri-reviewer/shri-2020-task-2/issues/4, но разница в том, что я хотел проверить всего лишь линтер для SEVERAL_H1. Думаю, что "❌ Линтер корректно валидирует блок warning: пройдено 10 из 40 тестов"- это ошибка автотестов. Могли бы перепроверить? 
![image](https://user-images.githubusercontent.com/17002069/70862150-9587cc80-1f49-11ea-8956-6be95049159f.png)

**Comment by chuuddo** [comment]
Предположу, что есть тесты, где подается валидный вход и на выходе ожидают пустой массив, что твой линтер и возвращает при отсутствии правил.
